#!/usr/bin/python
import os
import sys
from optparse import OptionParser

if not os.getuid() == 0:
   sys.exit("\nSubterfuge must be run as root\n")

#Thanks to n37div3r5 for the fix to run Subterfuge on a different port
def main():
   usage  = """
  Subterfuge courtesy of r00t0v3rr1d3 & 0sm0s1z
  Usage : subterfuge [OPTIONS]
  Default usage will run on 127.0.0.1:80"""
   version = '1.1'

   parser = OptionParser(usage=usage, version=version)
   parser.add_option("-s", "--serve", dest="alternative_addr", help="run subterfuge on an alternate IP:PORT")
   (options, args) = parser.parse_args()

   if options.alternative_addr:
      os.system("/usr/share/subterfuge/manage.py runserver " + options.alternative_addr)
   else:
      os.system("/usr/share/subterfuge/manage.py runserver 127.0.0.1:80")


if __name__ == '__main__':
    main()
